# Generated by Django 2.1 on 2018-08-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ausgaben',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summe', models.FloatField()),
                ('Typ', models.CharField(choices=[('1', 'LEH'), ('2', 'Drogerie'), ('3', 'Lieferant'), ('4', 'Essengehen'), ('5', 'Sonstiges für Wohnung'), ('6', 'Benzin'), ('7', 'Taschengeld'), ('8', 'Jette')], max_length=2)),
                ('Person', models.CharField(choices=[('1', 'Corinna'), ('2', 'Basti'), ('3', 'Gemeinsam')], max_length=2)),
                ('Beschreibung', models.CharField(max_length=200)),
                ('Zeitpunkt', models.DateField()),
                ('User', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='AusgabenPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summe', models.FloatField()),
                ('Typ', models.CharField(choices=[('1', 'LEH'), ('2', 'Drogerie'), ('3', 'Lieferant'), ('4', 'Essengehen'), ('5', 'Sonstiges für Wohnung'), ('6', 'Benzin'), ('7', 'Taschengeld'), ('8', 'Jette')], max_length=2)),
                ('Person', models.CharField(choices=[('1', 'Corinna'), ('2', 'Basti'), ('3', 'Gemeinsam')], max_length=2)),
            ],
        ),
    ]
