# Generated by Django 2.1 on 2018-08-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausgaben',
            name='Person',
            field=models.CharField(choices=[('Corinna', 'Corinna'), ('Basti', 'Basti'), ('Gemeinsam', 'Gemeinsam')], max_length=2),
        ),
        migrations.AlterField(
            model_name='ausgaben',
            name='Typ',
            field=models.CharField(choices=[('LEH', 'LEH'), ('Drogerie', 'Drogerie'), ('Lieferant', 'Lieferant'), ('Essengehen', 'Essengehen'), ('Sonstiges für Wohnung', 'Sonstiges für Wohnung'), ('Benzin', 'Benzin'), ('Taschengeld', 'Taschengeld'), ('Jette', 'Jette')], max_length=2),
        ),
        migrations.AlterField(
            model_name='ausgabenplan',
            name='Person',
            field=models.CharField(choices=[('Corinna', 'Corinna'), ('Basti', 'Basti'), ('Gemeinsam', 'Gemeinsam')], max_length=2),
        ),
        migrations.AlterField(
            model_name='ausgabenplan',
            name='Typ',
            field=models.CharField(choices=[('LEH', 'LEH'), ('Drogerie', 'Drogerie'), ('Lieferant', 'Lieferant'), ('Essengehen', 'Essengehen'), ('Sonstiges für Wohnung', 'Sonstiges für Wohnung'), ('Benzin', 'Benzin'), ('Taschengeld', 'Taschengeld'), ('Jette', 'Jette')], max_length=2),
        ),
    ]
