# Generated by Django 2.1 on 2018-09-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhdata', '0003_auto_20180829_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klassifizierung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feld', models.CharField(max_length=200)),
                ('Inhalt', models.CharField(max_length=200)),
                ('Typ', models.CharField(choices=[('LEH', 'LEH'), ('Drogerie', 'Drogerie'), ('Lieferant', 'Lieferant'), ('Essengehen', 'Essengehen'), ('Sonstiges für Wohnung', 'Sonstiges für Wohnung'), ('Benzin', 'Benzin'), ('Taschengeld', 'Taschengeld'), ('Jette', 'Jette')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaktion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Betrag', models.FloatField()),
                ('Typ', models.CharField(max_length=200)),
                ('Auftraggeber', models.CharField(max_length=200)),
                ('Buchungstext', models.CharField(max_length=200)),
                ('Verwendungszweck', models.CharField(max_length=200)),
                ('Buchung', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ausgaben',
        ),
        migrations.AlterField(
            model_name='ausgabenplan',
            name='Person',
            field=models.CharField(choices=[('Corinna', 'Corinna'), ('Basti', 'Basti'), ('Gemeinsam', 'Gemeinsam')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ausgabenplan',
            name='Typ',
            field=models.CharField(choices=[('LEH', 'LEH'), ('Drogerie', 'Drogerie'), ('Lieferant', 'Lieferant'), ('Essengehen', 'Essengehen'), ('Sonstiges für Wohnung', 'Sonstiges für Wohnung'), ('Benzin', 'Benzin'), ('Taschengeld', 'Taschengeld'), ('Jette', 'Jette')], max_length=21),
        ),
    ]
