# Generated by Django 2.1 on 2018-08-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhdata', '0004_auto_20180831_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaktion',
            name='Auftraggeber',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
