# Generated by Django 2.1 on 2018-08-31 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhdata', '0005_transaktion_auftraggeber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ausgaben',
        ),
    ]
