# Generated by Django 2.1 on 2018-08-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhdata', '0006_delete_ausgaben'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klassifizierung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feld', models.CharField(max_length=200)),
                ('Inhalt', models.CharField(max_length=200)),
                ('Typ', models.CharField(choices=[('LEH', 'LEH'), ('Drogerie', 'Drogerie'), ('Lieferant', 'Lieferant'), ('Essengehen', 'Essengehen'), ('Sonstiges für Wohnung', 'Sonstiges für Wohnung'), ('Benzin', 'Benzin'), ('Taschengeld', 'Taschengeld'), ('Jette', 'Jette')], max_length=200)),
            ],
        ),
    ]
